namespace Nwn.Toolset.Avalonia.Localization;

public enum BehaviorRowStringId
{
    Required,
    Choose,
    Clear,
    Close,
    ChooseValue,
    PreviewAudio,
    ChooseArtwork,
    GallerySearch,
    Sort,
    Option,
    Options,
    NoMatchingOptions,
    MatchingOptions,
    ShownOptions,
    SearchField,
    LoadingChoices,
    NoMatchingChoices,
    Choice,
    Choices,
    ChoiceLoaded,
    ChoicesLoaded,
    ShownChoices,
    All,
    DefaultOrder,
    NameAscending,
    NameDescending,
    IdAscending,
    IdDescending,
    ToggleField,
    ChangeField,
    NothingChosen,
}
