namespace Nwn.Toolset.Avalonia.Palettes;

/// <summary>Localized labels and messages used by the shared palette view.</summary>
public enum PaletteStringId
{
    Title,
    CustomSource,
    StandardSource,
    CustomSourceTooltip,
    StandardSourceTooltip,
    AutoTilePaint,
    ManualTilePaint,
    AutoTilePaintTooltip,
    ManualTilePaintTooltip,
    SearchWatermark,
    Categories,
    NewCategory,
    RenameCategory,
    DeleteCategory,
    PinToTop,
    UnpinFromTop,
    FileSelectedEntry,
    GoToCategory,
    GridSettings,
    PreviewSize,
    NoAreaOpen,
    NoAreaOpenDescription,
    EditBlueprint,
    EditCopy,
    DeleteBlueprint,
    ActionsForBlueprint,
    OneTile,
    ManyTiles,
    CategoryIn,
    SelectCategory,
    SearchMatches,
    FirstSearchMatches,
    CategoryTileCount,
    CategoryTileOverflow,
    BlueprintSearchMatches,
    BlueprintSearchOverflow,
    OpenAreaToPlace,
    TilesetNotLoaded,
    TilesetHasNoTiles,
    SelectTerrainToPaint,
    SelectTileToStamp,
    PreviewUnavailable
}
